//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormotsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulaire_ecv
    {
        public int Id { get; set; }
        public int IdDossier { get; set; }
        public Nullable<System.DateTime> DtCreation { get; set; }
        public Nullable<System.DateTime> DtEvaluation { get; set; }
        public Nullable<bool> PriseTraitementPsychotrope { get; set; }
        public Nullable<bool> AutrePrescriptionPsychotropes { get; set; }
        public Nullable<bool> ContinuerPratiquerRythme { get; set; }
        public Nullable<System.DateTime> DtMbi { get; set; }
        public Nullable<int> ScoreMbiEpuisementEmotionnel { get; set; }
        public string EpuisementEmotionnel { get; set; }
        public Nullable<int> ScoreMbiDepersonnalisation { get; set; }
        public string Depersonnalisation { get; set; }
        public Nullable<int> ScoreMbiAccomplissementPersonnel { get; set; }
        public string AccomplissementPersonnel { get; set; }
        public Nullable<System.DateTime> DtRud { get; set; }
        public Nullable<int> NiveauRisqueRud { get; set; }
        public string EvaluationRisqueRud { get; set; }
        public string CommentairesLibres { get; set; }
        public string ActionsProposeesRud { get; set; }
    
        public virtual dossiers dossiers { get; set; }
    }
}
