//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormotsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulaire_cda
    {
        public int Id { get; set; }
        public int IdDossier { get; set; }
        public Nullable<System.DateTime> DtCreation { get; set; }
        public string MotifAppelInitial { get; set; }
        public string MotifAppelInitialAutre { get; set; }
        public Nullable<bool> ProblematiqueComplementaire { get; set; }
        public string TypeProblematiqueComplementaire { get; set; }
        public string TypeProblematiqueComplementaireAutre { get; set; }
        public string Addictions { get; set; }
        public string AntecedentsPersonnels { get; set; }
        public Nullable<bool> AntecedentsFamiliauxTa { get; set; }
        public string CommentairesLibres { get; set; }
    
        public virtual dossiers dossiers { get; set; }
    }
}
