//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormotsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulaire_act
    {
        public int Id { get; set; }
        public int IdDossier { get; set; }
        public Nullable<System.DateTime> DtCreation { get; set; }
        public Nullable<System.DateTime> DtDebutEntretien { get; set; }
        public Nullable<System.DateTime> DtFinEntretien { get; set; }
        public Nullable<System.DateTime> Dt1ErContactMaAccueil { get; set; }
        public Nullable<System.DateTime> Dt1ErContactMeMa { get; set; }
        public Nullable<System.DateTime> DtMeAccueil { get; set; }
        public string Jour1ErContact { get; set; }
        public string DepartementExerciceMa { get; set; }
        public Nullable<int> SuggestionAppelMots { get; set; }
        public string AutreSuggestionAppelMots { get; set; }
        public string CommentairesLibres { get; set; }
        public Nullable<int> ContactPar1ErContactMaAccueil { get; set; }
        public Nullable<int> ContactPar1ErContactMeMa { get; set; }
    
        public virtual dossiers dossiers { get; set; }
    }
}
