//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormotsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulaire_seo
    {
        public int Id { get; set; }
        public int IdDossier { get; set; }
        public Nullable<System.DateTime> DtCreation { get; set; }
        public string NumeroEntretien { get; set; }
        public Nullable<System.DateTime> DateEntretien { get; set; }
        public Nullable<int> TypeEntretien { get; set; }
        public Nullable<int> DureeEntretien { get; set; }
        public Nullable<bool> TravailConnexeEntretien { get; set; }
        public Nullable<int> DureeDeplacement { get; set; }
        public Nullable<int> RechercheDocumentation { get; set; }
        public Nullable<int> ContactsExternesMots { get; set; }
        public string AutreTravailConnexe { get; set; }
        public string AppelContactInterneMots { get; set; }
        public string MotifAppelContactInterneMots { get; set; }
        public string Orientations { get; set; }
        public string OrientationAutre { get; set; }
        public Nullable<bool> ArretMaladiePreconise { get; set; }
        public string CommentairesLibres { get; set; }
    
        public virtual dossiers dossiers { get; set; }
    }
}
