//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormotsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulaire_cfp
    {
        public int Id { get; set; }
        public int IdDossier { get; set; }
        public Nullable<System.DateTime> DtCreation { get; set; }
        public Nullable<int> StatutCivil { get; set; }
        public Nullable<bool> RevenusSeulsFoyer { get; set; }
        public Nullable<bool> PersonnesACharge { get; set; }
        public Nullable<bool> GrossesseEnCours { get; set; }
        public Nullable<bool> EnfantsMineurs { get; set; }
        public Nullable<int> NombreEnfantsMineurs { get; set; }
        public Nullable<int> ExerciceProfessionnel { get; set; }
        public Nullable<int> PrecisionsExerciceProfessionnel { get; set; }
        public Nullable<int> FonctionHospitaliere { get; set; }
        public Nullable<int> Specialite { get; set; }
        public Nullable<int> NombreHeuresHebdoMoyen { get; set; }
        public Nullable<int> CongesAnnuels { get; set; }
        public Nullable<bool> ActivitesFormation { get; set; }
        public Nullable<bool> SavoirDireNon { get; set; }
        public Nullable<bool> AutreMedecinTraitant { get; set; }
        public Nullable<bool> Automedication { get; set; }
        public Nullable<bool> SuiviDepistage { get; set; }
        public string ActivitesLoisirs { get; set; }
        public Nullable<bool> PrevoyanceAssurance { get; set; }
        public Nullable<bool> CarmfAJour { get; set; }
        public Nullable<bool> UrssafAJour { get; set; }
        public Nullable<bool> OrdreMedecinAJour { get; set; }
        public string CommentairesLibres { get; set; }
    
        public virtual dossiers dossiers { get; set; }
    }
}
